release-schema.json: add accessDetailsURL and unofficialTranslation
open-contracting/ocds_documentation_extension pull request #19
Opened 2023-04-25 15:18 UTC by odscjen

In the example I used a field that will be deprecated in 1.2 so that the tests would pass, not sure if that should be changed to the 1.2 field instead (`language` vs `languages`)

2023-04-27 05:16 UTC, duncandewhurst requested changes

2023-04-27 05:16 UTC, duncandewhurst commented on README.md
> +
Based on the feedback in other PRs, I think this can be removed: the extension existed already so we don't need to the EU legal context to justify its existence.

```suggestion
```

2023-04-27 05:16 UTC, duncandewhurst commented on release-schema.json
> +          "description": "A web address containg a description of any special arrangements needed to access the document.",
```suggestion
          "description": "A web address with information on any special arrangements needed to access the document.",
```

2023-04-27 05:16 UTC, duncandewhurst commented on release-schema.json
> +          "description": "A true/false field to indicate if the language of the document is an unofficial translation.",
Per the style guide:

```suggestion
          "description": "Whether the document is an unofficial translation.",
```

2023-06-07 04:14 UTC, duncandewhurst approved these changes

2023-06-07 19:31 UTC, jpmckinney commented on README.md
> +* Indicate if the document is an unofficial translation
```suggestion
* Indicate whether the document is an unofficial translation
```

2023-06-07 19:31 UTC, jpmckinney commented on README.md
> +* Add `accessDetailsURL` and `unofficialTranslation`.
```suggestion
* Add `accessDetailsURL` and `unofficialTranslation` fields.
```

2023-06-07 19:31 UTC, jpmckinney commented on release-schema.json
> +          "title": "Access details",
```suggestion
          "title": "Access details URL",
```

2023-06-07 19:31 UTC, jpmckinney commented on release-schema.json
> +          "description": "A web address with information on any special arrangements needed to access the document.",
```suggestion
          "description": "A web address for information on any special arrangements needed to access the document.",
```

2023-06-07 19:33 UTC, jpmckinney approved these changes

2023-06-07 19:33 UTC, merged