release-schema.json: convert unofficialTranslation from boolean to ar…
open-contracting/ocds_documentation_extension pull request #20
Opened 2023-08-04 15:09 UTC by odscjen

…ray of languages

closes https://github.com/open-contracting/european-union-support/issues/189

2023-08-10 03:10 UTC, duncandewhurst requested changes
If you're happy with my suggestions, you can request a review from James once you've committed them.

2023-08-10 03:10 UTC, duncandewhurst commented on README.md
> +* Provide any unofficial languages the document is provided in
```suggestion
* Indicate the languages in which unofficial translations of the document are available
```

2023-08-10 03:10 UTC, duncandewhurst commented on release-schema.json
> +          "description": "The languages used in unofficial translations of the document, from the open [language](https://standard.open-contracting.org/{{version}}/{{lang}}/schema/codelists/#language
```suggestion
          "description": "The languages in which unofficial translations of the document are available, from the open [language](https://standard.open-contracting.org/{{version}}/{{lang}}/schema/codelists/#language) codelist. A [BCP47 language tag](https://www.w3.org/International/articles/language-tags/) is allowed, if there is a user need for the additional information.",
```

2023-08-10 14:44 UTC, jpmckinney approved these changes

2023-08-10 14:44 UTC, merged

2023-08-11 02:45 UTC, jpmckinney commented
Ah, we need to add the `language.csv` codelist to this extension, which is only introduced in 1.2.